"""Store envelope-encrypted paid-source credentials and consent history.

Revision ID: 20260906_0005
Revises: 20260906_0004
"""
from alembic import op

revision = "20260906_0005"
down_revision = "20260906_0004"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute("""CREATE TABLE paid_source_credentials (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id TEXT NOT NULL, provider TEXT NOT NULL, ciphertext BYTEA NOT NULL, data_nonce BYTEA NOT NULL, encrypted_data_key BYTEA NOT NULL, kek_nonce BYTEA NOT NULL, kek_version TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, rotated_at TIMESTAMPTZ, UNIQUE(user_id, provider))""")
    op.execute("CREATE INDEX ix_paid_source_credentials_user_provider ON paid_source_credentials (user_id, provider)")

def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS paid_source_credentials")
