"""Queue answers affected by corpus document changes.

Revision ID: 20260906_0004
Revises: 20260906_0003
Create Date: 2026-09-06
"""

from alembic import op

revision = "20260906_0004"
down_revision = "20260906_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE qa_review_queue (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            qa_log_id BIGINT NOT NULL REFERENCES qa_log(id) ON DELETE CASCADE,
            changed_document_id BIGINT NOT NULL REFERENCES corpus_documents(id) ON DELETE CASCADE,
            relationship_types TEXT[] NOT NULL DEFAULT '{}',
            status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'dismissed')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_at TIMESTAMPTZ,
            UNIQUE (qa_log_id, changed_document_id)
        )
        """
    )
    op.execute("CREATE INDEX ix_qa_review_queue_status_created ON qa_review_queue (status, created_at)")
    op.execute("CREATE INDEX ix_qa_review_queue_qa_log_id ON qa_review_queue (qa_log_id)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS qa_review_queue")
