"""Add corpus_staging, session_uploads, and session_upload_chunks tables.

Revision ID: 20260907_0009
Revises: 20260906_0008
Create Date: 2026-09-07
"""

from alembic import op

revision = "20260907_0009"
down_revision = "20260906_0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE corpus_staging (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            url TEXT NOT NULL,
            domain TEXT NOT NULL,
            title TEXT NOT NULL,
            topic TEXT NOT NULL,
            jurisdiction TEXT NOT NULL CHECK (jurisdiction IN ('IN', 'INTL')),
            body_text TEXT NOT NULL,
            source_hash TEXT NOT NULL UNIQUE,
            discovered_via TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'promoted', 'rejected')),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed_at TIMESTAMPTZ,
            reviewed_by TEXT,
            rejection_reason TEXT,
            CONSTRAINT corpus_staging_closure_evidence CHECK (
                (status = 'pending_review' AND reviewed_at IS NULL AND reviewed_by IS NULL AND rejection_reason IS NULL)
                OR (status = 'promoted' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND rejection_reason IS NULL)
                OR (status = 'rejected' AND reviewed_at IS NOT NULL AND reviewed_by IS NOT NULL AND rejection_reason IS NOT NULL)
            )
        )
        """
    )
    op.execute("CREATE INDEX ix_corpus_staging_status ON corpus_staging (status)")
    op.execute("CREATE INDEX ix_corpus_staging_source_hash ON corpus_staging (source_hash)")

    op.execute(
        """
        CREATE TABLE session_uploads (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            filename TEXT NOT NULL,
            content_type TEXT NOT NULL,
            char_count INTEGER NOT NULL,
            uploaded_by TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            expires_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute("CREATE INDEX ix_session_uploads_session_id ON session_uploads (session_id)")
    op.execute("CREATE INDEX ix_session_uploads_expires_at ON session_uploads (expires_at)")

    op.execute(
        """
        CREATE TABLE session_upload_chunks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            upload_id BIGINT NOT NULL REFERENCES session_uploads(id) ON DELETE CASCADE,
            chunk_text TEXT NOT NULL,
            embedding vector(1024)
        )
        """
    )
    op.execute("CREATE INDEX ix_session_upload_chunks_upload_id ON session_upload_chunks (upload_id)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS session_upload_chunks")
    op.execute("DROP TABLE IF EXISTS session_uploads")
    op.execute("DROP TABLE IF EXISTS corpus_staging")
