"""Create corpus, classification, QA, escalation, and grant tables.

Revision ID: 20260905_0001
Revises:
Create Date: 2026-09-05
"""

from alembic import op

revision = "20260905_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.execute(
        """
        CREATE TABLE corpus_documents (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instrument TEXT NOT NULL,
            section TEXT NOT NULL,
            jurisdiction TEXT NOT NULL CHECK (jurisdiction IN ('IN', 'INTL')),
            source_url TEXT NOT NULL,
            source_hash TEXT NOT NULL,
            full_text TEXT NOT NULL,
            version_tag TEXT NOT NULL,
            retrieved_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            is_active BOOLEAN NOT NULL DEFAULT TRUE
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_corpus_documents_jurisdiction "
        "ON corpus_documents USING btree (jurisdiction)"
    )
    op.execute(
        "CREATE INDEX ix_corpus_documents_is_active "
        "ON corpus_documents USING btree (is_active)"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_corpus_documents_active_instrument "
        "ON corpus_documents (instrument) WHERE is_active"
    )

    op.execute(
        """
        CREATE TABLE corpus_chunks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id BIGINT NOT NULL REFERENCES corpus_documents(id) ON DELETE CASCADE,
            chunk_text TEXT NOT NULL,
            embedding vector(1024),
            text_search TSVECTOR GENERATED ALWAYS AS (
                to_tsvector('simple'::regconfig, chunk_text)
            ) STORED,
            tags TEXT[] NOT NULL DEFAULT '{}'
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_corpus_chunks_document_id "
        "ON corpus_chunks USING btree (document_id)"
    )
    op.execute(
        "CREATE INDEX ix_corpus_chunks_text_search "
        "ON corpus_chunks USING gin (text_search)"
    )
    op.execute(
        "CREATE INDEX ix_corpus_chunks_embedding_hnsw "
        "ON corpus_chunks USING hnsw (embedding vector_cosine_ops)"
    )

    op.execute(
        """
        CREATE TABLE corpus_change_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            document_id BIGINT NOT NULL REFERENCES corpus_documents(id) ON DELETE CASCADE,
            previous_version_tag TEXT,
            new_version_tag TEXT NOT NULL,
            detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            reviewed BOOLEAN NOT NULL DEFAULT FALSE
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_corpus_change_log_document_id "
        "ON corpus_change_log USING btree (document_id)"
    )
    op.execute(
        "CREATE INDEX ix_corpus_change_log_reviewed "
        "ON corpus_change_log USING btree (reviewed)"
    )

    op.execute(
        """
        CREATE TABLE classification_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            answers_json JSONB NOT NULL,
            category TEXT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_classification_results_session_id "
        "ON classification_results USING btree (session_id)"
    )

    op.execute(
        """
        CREATE TABLE qa_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            question TEXT NOT NULL,
            jurisdiction_mode TEXT NOT NULL,
            retrieved_chunk_ids TEXT[] NOT NULL DEFAULT '{}',
            reranker_scores JSONB NOT NULL DEFAULT '{}'::jsonb,
            answer_json JSONB NOT NULL,
            confidence NUMERIC(5, 4) CHECK (confidence IS NULL OR confidence >= 0 AND confidence <= 1),
            abstained BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            request_id TEXT NOT NULL
        )
        """
    )
    op.execute("CREATE INDEX ix_qa_log_session_id ON qa_log USING btree (session_id)")
    op.execute("CREATE INDEX ix_qa_log_request_id ON qa_log USING btree (request_id)")
    op.execute("CREATE INDEX ix_qa_log_created_at ON qa_log USING btree (created_at)")

    op.execute(
        """
        CREATE TABLE escalations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id TEXT NOT NULL,
            question TEXT NOT NULL,
            reason TEXT NOT NULL,
            priority TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'open',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute("CREATE INDEX ix_escalations_session_id ON escalations USING btree (session_id)")
    op.execute("CREATE INDEX ix_escalations_status ON escalations USING btree (status)")

    op.execute(
        """
        CREATE TABLE paid_source_grants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id TEXT NOT NULL,
            provider TEXT NOT NULL,
            granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            revoked_at TIMESTAMPTZ,
            consent_log_json JSONB NOT NULL DEFAULT '{}'::jsonb
        )
        """
    )
    op.execute("CREATE INDEX ix_paid_source_grants_user_id ON paid_source_grants USING btree (user_id)")
    op.execute("CREATE INDEX ix_paid_source_grants_provider ON paid_source_grants USING btree (provider)")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS paid_source_grants")
    op.execute("DROP TABLE IF EXISTS escalations")
    op.execute("DROP TABLE IF EXISTS qa_log")
    op.execute("DROP TABLE IF EXISTS classification_results")
    op.execute("DROP TABLE IF EXISTS corpus_change_log")
    op.execute("DROP TABLE IF EXISTS corpus_chunks")
    op.execute("DROP TABLE IF EXISTS corpus_documents")
