"""Add a PostgreSQL adjacency graph and seed corpus relationships.

Revision ID: 20260906_0002
Revises: 20260905_0001
Create Date: 2026-09-06
"""

from alembic import op

revision = "20260906_0002"
down_revision = "20260905_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # An adjacency table keeps graph data in the existing Postgres transaction,
    # backup, and access-control boundary while still allowing recursive CTEs.
    op.execute(
        """
        CREATE TABLE graph_entities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL CHECK (entity_type IN (
                'Instrument', 'Section', 'Treaty', 'FormulationCategory', 'RegistryRecord'
            )),
            name TEXT NOT NULL,
            properties JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (entity_type, name)
        )
        """
    )
    op.execute("CREATE INDEX ix_graph_entities_type_name ON graph_entities (entity_type, name)")
    op.execute(
        """
        CREATE TABLE graph_relationships (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_entity_id BIGINT NOT NULL REFERENCES graph_entities(id) ON DELETE CASCADE,
            target_entity_id BIGINT NOT NULL REFERENCES graph_entities(id) ON DELETE CASCADE,
            relationship_type TEXT NOT NULL CHECK (relationship_type IN (
                'CITES', 'SUPERSEDES', 'APPLIES_TO_CATEGORY', 'CROSS_REFERENCES'
            )),
            properties JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CHECK (source_entity_id <> target_entity_id),
            UNIQUE (source_entity_id, target_entity_id, relationship_type)
        )
        """
    )
    op.execute(
        "CREATE INDEX ix_graph_relationships_source_type "
        "ON graph_relationships (source_entity_id, relationship_type)"
    )
    op.execute(
        "CREATE INDEX ix_graph_relationships_target_type "
        "ON graph_relationships (target_entity_id, relationship_type)"
    )

    # The graph layer is intentionally separate from corpus_document versions:
    # these canonical entities survive corpus re-ingestion and document revisions.
    op.execute(
        """
        INSERT INTO graph_entities (entity_type, name, properties)
        VALUES
            ('Instrument', 'Patents Act, 1970', '{"jurisdiction":"IN"}'::jsonb),
            ('Section', 'Patents Act, 1970 - Section 3(p)',
             '{"instrument":"Patents Act, 1970","section":"Section 3(p)"}'::jsonb),
            ('FormulationCategory', 'classical', '{}'::jsonb),
            ('Instrument', 'Biological Diversity Act, 2002', '{"jurisdiction":"IN"}'::jsonb),
            ('Section', 'Biological Diversity Act, 2002 - Section 21',
             '{"instrument":"Biological Diversity Act, 2002","section":"Section 21"}'::jsonb),
            ('Treaty', 'WIPO GRATK Treaty',
             '{"full_name":"WIPO Treaty on Intellectual Property, Genetic Resources and Associated Traditional Knowledge"}'::jsonb),
            ('Instrument', 'Drugs and Cosmetics Act, 1940', '{"jurisdiction":"IN"}'::jsonb),
            ('Section', 'Drugs and Cosmetics Act, 1940 - Formulation categories and standards',
             '{"instrument":"Drugs and Cosmetics Act, 1940"}'::jsonb),
            ('RegistryRecord', 'People''s Biodiversity Registers', '{"jurisdiction":"IN"}'::jsonb)
        ON CONFLICT (entity_type, name) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO graph_relationships (source_entity_id, target_entity_id, relationship_type)
        SELECT source.id, target.id, edge.relationship_type
        FROM (
            VALUES
                ('Section', 'Patents Act, 1970 - Section 3(p)',
                 'FormulationCategory', 'classical', 'APPLIES_TO_CATEGORY'),
                ('Instrument', 'Biological Diversity Act, 2002',
                 'Treaty', 'WIPO GRATK Treaty', 'CROSS_REFERENCES')
        ) AS edge(source_type, source_name, target_type, target_name, relationship_type)
        JOIN graph_entities AS source
          ON source.entity_type = edge.source_type AND source.name = edge.source_name
        JOIN graph_entities AS target
          ON target.entity_type = edge.target_type AND target.name = edge.target_name
        ON CONFLICT (source_entity_id, target_entity_id, relationship_type) DO NOTHING
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS graph_relationships")
    op.execute("DROP TABLE IF EXISTS graph_entities")
